spring:
  config:
    import: optional:classpath:application-secrets.properties

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${server.ssl.key-store}
    key-store-password: ${server.ssl.key-store-password}
    key-store-type: PKCS12
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024 
    mime-types: text/html, text/xml, text/plain, text/css, application/json, application/javascript
